version: "3.8"
services:
  fehape:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.app
    image: php:7.4-fpm-alpine3.15
    container_name: fehape
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    expose:
      - 9000
    networks:
      - defaultnetwork
    environment:
      - DEBUG=1
      - PUBLIC_BASEURL=http://localhost:8000/
      - ADMIN_BASEURL=http://localhost:8001/

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - '8000:8000'
      - '8001:8001'
    volumes:
      - ./src:/var/www
      - ./config:/etc/nginx/conf.d
    networks:
      - defaultnetwork
    depends_on:
      - app

networks:
  defaultnetwork: 